name: inspection-report-manager
project_name: operations
region: us-east1

autoscaling:
  minReplicas: 0
  maxReplicas: 5

containerConcurrency: 10
timeoutSeconds: 3000

resources:
  limits:
    cpu: "1"
    memory: "512Mi"

environment_variables:
  NODE_ENV: production
  SLACK_USE_SOCKET_MODE: "false"

environment_variable_secrets:
  - name: SLACK_SIGNING_SECRET
    secret_name: slack-signing-secret
  - name: SLACK_BOT_TOKEN
    secret_name: slack-bot-token
  - name: SLACK_APP_TOKEN
    secret_name: slack-app-token
  - name: JIRA_API_TOKEN
    secret_name: jira-api-token
  - name: JIRA_EMAIL
    secret_name: jira-email
  - name: JIRA_BASE_URL
    secret_name: jira-base-url
  - name: SLACK_TEST_CHANNEL_ID
    secret_name: slack-test-channel-id
